### PR TITLE
Implement `collections_fetch()`

### LINKED ISSUE #10: Thin wrapper around `rstac::collections()` to automatically page the NASA STAC API?
The NASA STAC API returns only 10 collections in [a page for a given catalogue](https://cmr.earthdata.nasa.gov/stac/LPCLOUD), with a `rel:next` item pointing to the next page with the next 10 collections in it. This is non-standard, so using `rstac::collections()` doesn't provide a way to get a list of all collections. This affects the search-ability of the NASA STAC from R. As you can see below only 10 collections are returned although there are many more in the `POCLOUD` catalogue:

``` r
library(rstac)

stac("https://cmr.earthdata.nasa.gov/stac/POCLOUD/") |> 
  collections() |> 
  get_request()
#> ###Collections
#> - collections (10 item(s)):
#>   - SEAGLIDER_GUAM_2019.vV1
#>   - AQUARIUS_L2_SSS_CAP_V5.v5.0
#>   - AQUARIUS_L3_SSS_RAINCORRECTED_CAP_7DAY_V5.v5.0
#>   - AQUARIUS_L3_SSS_RAINCORRECTED_CAP_MONTHLY_V5.v5.0
#>   - AQUARIUS_L3_SSS_CAP_7DAY_V5.v5.0
#>   - AQUARIUS_L3_SSS_CAP_MONTHLY_V5.v5.0
#>   - AQUARIUS_L3_WIND_SPEED_CAP_7DAY_V5.v5.0
#>   - AQUARIUS_L3_WIND_SPEED_CAP_MONTHLY_V5.v5.0
#>   - AQUARIUS_ANCILLARY_CELESTIALSKY_V1.v1
#>   - AQUARIUS_L2_SSS_V5.v5.0
#> - field(s): id, stac_version, description, license, type, links, collections
```

<sup>Created on 2024-04-03 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

We could write a thin wrapper that does the paging and returns the full list of collections? `edl_nasa_collections()`? It would then be used like:

```r
stac("https://cmr.earthdata.nasa.gov/stac/POCLOUD/") |> 
  edl_nasa_collections() |> 
  get_request()
```

### PR DESCRIPTION
**Pull request by ateucher**
Closes #10, but rather than a wrapper, implements our version of `collections_fetch()`. This would ideally live in rstac, but this implementation is useable now. 

Issue open [in rstac](https://github.com/brazil-data-cube/rstac/issues/154) to add it there (though the implementation would be different in rstac as we could leverage internal methods)

### CODE REVIEW

**Comment by ateucher** [comment]
Note: I've also exported `edl_stac_urls()` (#9), which I think is a handy function to have available to users.

**Review by cboettig — COMMENTED** [review]
Looks great! thanks @ateucher . Can you add yourself as a `ctb` in the DESCRIPTION and drop a comment in NEWS.md?

**Comment by ateucher** [comment]
@cboettig some failures related to auth, but it looks like the `EARTHDATA_USE` and `EARTHDATA_PASSWORD` are set?

**Comment by cboettig** [comment]
yeah the auth issue looks surprising, I need to take a look.  maybe is related to secrets but I thought I had public credentials for this in place. no errors locally?

**Comment by cboettig** [comment]
ah looks like I used encrypted secrets, and GitHub says:

> Anyone with collaborator access to this repository can use these secrets and variables for actions. They are not passed to workflows that are triggered by a pull request from a fork.

so should be fine once merged.

**Comment by ateucher** [comment]
> yeah the auth issue looks surprising, I need to take a look. maybe is related to secrets but I thought I had public credentials for this in place. no errors locally?

Yup, everything passed fine locally

**Pull request merged**
